### ISSUE TITLE
Why there's an error when invoking the contract which is already invoked before

### ISSUE THREAD

**Issue by BigBang019** [hyperledger/fabric-chaincode-java#219]
Environment: Hyperledger Fabric release 2.2
chaincode **A**:
```java
@Transaction()
public String invokeOtherContract(final Context ctx, final String chaincodeName, final String method) {
    System.out.printf("\n%s\n", chaincodeName);
    Response resp = ctx.getStub().invokeChaincode(chaincodeName, Arrays.asList(method.getBytes()));
    String payload = new String(resp.getPayload(), StandardCharsets.UTF_8);
    return payload;
}
@Transaction()
public String helloworld(final Context ctx){
    System.out.println("helloworld");
    return "helloworld";
}
```

chaincode B:
```java
@Transaction()
public String callback(final Context ctx){
    Response resp = ctx.getStub().invokeChaincode("A", Arrays.asList("helloworld".getBytes()));
    return new String(resp.getPayload(), StandardCharsets.UTF_8);
}
```
I submit a transaction calling **A**.invokeOtherContract, an error occured.
According to https://lists.hyperledger.org/g/fabric/topic/question_about/87787297?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,87787297,previd=1639806725290257427,nextid=1638892803487662689&previd=1639806725290257427&nextid=1638892803487662689, a chaincode has a unique identifier in the network when it is running.

How this error happen? I'm quite confused with the way (in code) this error happens.

**Comment by BigBang019** [comment]
Detail:
I called **A**.invokeOtherContract, with args chaincodeName=**B**, method=**callback**.
Step1: Invocation of **A**.invokeOtherContract is successful. Then **A** sends a message to **B** to invoke callback function.
Step2: In **callback** function, B trying to invoke **A**.helloworld. Then an error occured.

Logs of **A** docker container:

![image](https://user-images.githubusercontent.com/46477713/146717973-1b6e7f52-f511-455e-96d2-1ae9a429ec23.png)


Logs of **B** docker container:

![image](https://user-images.githubusercontent.com/46477713/146717911-f6b796ff-260b-44ce-9359-99dfe8e98b46.png)

**Comment by BigBang019** [comment]
@mbwhite Yes, exactly.
**B** has method callA, which will invoke some method in **A**.
**A** has method callB and helloworld. callB is a method to call **B**.callA, and helloworld is just a method which returns "helloworld".

Both scenarios fail:
A.callB --> B.callA --> A.callB fail
A.callB --> B.callA --> A.helloworld fail.

**Comment by mbwhite** [comment]
I'm reviewing old issues; I'm going to close this one as 'not supported'  - the cyclical calling of transactions isn't supported by the core Fabric code. 

Within a single chaincode, the code can call other other functions whether they are marked as transactions as not.

As always please re-open if needed.
