### ISSUE TITLE
Upgrade failed to Fabric 1.4.12 since hyperledger/fabric-javaenv:amd64-1.4.12 missing. Make a 1.4.12 release

### ISSUE THREAD

**Issue by kencodible** [hyperledger/fabric-chaincode-java#221]
While upgrading my 1.4.4 Fabric deployment, with Java chaincode, to 1.4.12 the installation of chaincode on the upgraded 1.4.12 peer failed due to the Docker image `hyperledger/fabric-javaenv:amd64-1.4.12` not being found.

The specific error follows:
```
Error: could not assemble transaction, 
      err proposal response was not successful, error code 500, 
      msg error starting container: 
          error starting container: 
              Failed to generate platform-specific docker build: 
                  Failed to pull hyperledger/fabric-javaenv:amd64-1.4.12: 
                      API error (404): manifest for hyperledger/fabric-javaenv:amd64-1.4.12 not found: 
                          manifest unknown: manifest unknown
```

I'd be happy to build this locally if I can and push my own `hyperledger/fabric-javaenv:amd64-1.4.12` image to a repository.

**Comment by mbwhite** [comment]
@kencodible thanks for the report;  


The quickest solution would be to pull down the last fabric-javaenv at 1.4 (https://hub.docker.com/layers/hyperledger/fabric-javaenv/1.4.8/images/sha256-93bebc77e0e5c998b0a3dad5cdb1ff82011f15154b191671a0c8b42b7db44d2e?context=explore) and retag that as the 1.4.12

As version 2 is now the LTS stream we aren't releasing new versions of the 1.4 chaincode. libraries.

**Comment by kencodible** [comment]
Thought so. Thanks @mbwhite, I'll try that first.
