### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by BeniMori** [hyperledger/fabric-chaincode-java#229]
* What went wrong:
Execution failed for task ':fabric-chaincode-docker:buildImage'.
> Could not build image: The command '/bin/bash -c gradle     clean     fabric-chaincode-protos:build     fabric-chaincode-protos:publishToMavenLocal     fabric-chaincode-shim:build     fabric-chaincode-shim:publishToMavenLocal     -x javadoc     -x test     -x checkstyleMain     -x checkstyleTest     -x dependencyCheckAnalyze' returned a non-zero code: 1

any suggestions how to solve this issue?

**Comment by gqqnbig** [comment]
check your JAVA_HOME environment variable or javac --version. The required version is [jdk8](https://github.com/hyperledger/fabric-chaincode-java/blob/v2.3.1/README.md#building-and-testing).

But I do believe build.gradle can be revised to specify the jdk version. https://docs.gradle.org/current/userguide/toolchains.html

**Comment by gqqnbig** [comment]
What exactly do you want to build? For me I only want to build the jar of fabric-chaincode-shim. I used `./gradlew build -x javadoc` and it worked. How about you?

**Comment by mbwhite** [comment]
Hello; if you still have issues with building the repo or contract code please do open an issue with the problems you're seeing.
