### ISSUE TITLE
Fabric-shim-java needs to return a nested exception

### ISSUE THREAD

**Issue by deeptiraom** [hyperledger/fabric-chaincode-java#247]
Its observed that the fabric-chaincode-shim throws ContractException in case of exception in Chaincode however it needs to return the actual cause nested / wrapped inside the chaincode exception.
This is required to fetch the nested exception which is the actual cause in the client sdk adapter when used to run marvin

**Comment by deeptiraom** [comment]
I am trying to fetch the nested exception in the client sdk but its not present:
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/41100100/174739330-09b7579b-95ff-42ff-acc5-dccd97a362b6.png">

**Comment by jt-nti** [comment]
There's an example of handling errors such as the sample asset not found in the REST sample which may be useful...
https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/rest-api-typescript/src/errors.ts
