### ISSUE TITLE
AdoptOpenJDK has gone EOS

### ISSUE THREAD

**Issue by benjsmi** [hyperledger/fabric-chaincode-java#256]
As per https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/, OpenJDK is no more or will be shortly.  A different way of saying this is that AdoptOpenJDK has gone End of Service.

https://adoptium.net/ is the new location to get these binaries.

The source code location of this is https://github.com/hyperledger/fabric-chaincode-java/blob/main/fabric-chaincode-docker/Dockerfile#L57.

It's worth putting into this issue that the Fabric Java SDK will need to compile/run in the updated environment, which will potentially have an impact on the amount of time it takes to finish this task.  That is, Fabric SDK code may need to be updated before or with this change and I'm not sure how much code change is needed.

**Comment by mbwhite** [comment]
JVM updated for the 2.5 release

https://github.com/hyperledger/fabric-chaincode-java/commit/37bebee7fced815336960504cb880083a7d40a52

**Comment by benjsmi** [comment]
Is this going to be backported to v2.2 given that it's still your Long Term Service (LTS) release?
